In [32]:
#Problema 1

def leevalida(m,M,txt):
    s=(input(txt))
    x=len(s)
    while(not m<= x <= M):
        s=(input("Error, ingrese denuevo: "))
        x=len(s)
    return s


def eliminado(c):
    s="aeiou"
    if c in s:
        return "-"
    if c==" ":
        return ""

    else:
        return c


s=leevalida(1,1000,"Ingrese su cadena: ")
s=s.lower()
sol=""
for k in s:
    sol+=eliminado(k)

print(sol)





Ingrese su cadena:  hola aaa


h-l----


In [28]:
#Problema 2

def es_lider(k,l):
    if(k==len(l)-1):
        return False
        
    for i in range(k+1,len(l)):
        if(l[i]>l[k]):
            return False

    return True


def es_primo(p):
    if(p==0):
        return False
    if(p==1):
        return True
    for i in range(2,p):
        if(p%i==0):
            return False
    return True
    
def primos_n(n):
    l=[]
    for i in range(n+1):
        if(es_primo(i)):
            l.append(i)
    return l


n=int(input("n: "))
numeros=[]
maxi=-1
for i in range(n):
    x=int(input(f"n{i+1}=")) 
    if(x>maxi):
        maxi=x
    numeros.append(x)

sol=[]
primos=primos_n(maxi)
for i in range(n):
    s=[]
    for p in primos:
        if(p not in s and numeros[i]-p in primos):
            print(f"Pareja de primos de {numeros[i]} son: {p} {numeros[i]-p}")
            sol.append(p)
            s.append(p)
            s.append(numeros[i]-p)
            sol.append(numeros[i]-p)
print()
for i in range(len(sol)):
    if(es_lider(i,sol)):
        print(sol[i],end=" ")
print()
print(sol)

n:  4
n1= 18
n2= 34
n3= 45
n4= 2


Pareja de primos de 18 son: 1 17
Pareja de primos de 18 son: 5 13
Pareja de primos de 18 son: 7 11
Pareja de primos de 34 son: 3 31
Pareja de primos de 34 son: 5 29
Pareja de primos de 34 son: 11 23
Pareja de primos de 34 son: 17 17
Pareja de primos de 45 son: 2 43
Pareja de primos de 2 son: 1 1

43 1 
[1, 17, 5, 13, 7, 11, 3, 31, 5, 29, 11, 23, 17, 17, 2, 43, 1, 1]


In [14]:
#Problema 3

import numpy as np

def leevalida(m,M,txt):
    x=int(input(txt))
    while(not m<= x <= M):
        x=int(input("Error, ingrese denuevo: "))
    return x



n=leevalida(2,10,"n: ")
A=np.zeros((n,n))
for i in range(n):
    A[0][i]=leevalida(-9,9,f"A[0][{i+1}]=")

for i in range(1,n):
    for j in range(n):
        if(j>=i):
            t=A[i-1][j-1]+A[i-1][j]
            if(t>=10):
                t=t%10
            A[i][j]=t

print(A)
                






n:  4
A[0][1]= 1
A[0][2]= -2
A[0][3]= 9
A[0][4]= 8


[[ 1. -2.  9.  8.]
 [ 0. -1.  7.  7.]
 [ 0.  0.  6.  4.]
 [ 0.  0.  0.  0.]]
