# CERTAMEN 2 PROGRAMACIÓN

NOMBRE ALUMNO: Jose Benjamin Junemann Vielma

MATRÍCULA    : 2024436813

SECCIÓN      : 0

PROFESOR     : Emo


In [1]:
'''
Observaciones: Sección exclusiva para el comentarios de él/la revisor/a.

Puntaje : Sección exclusiva para el comentarios de él/la revisor/a.
'''
#  CÓDIGO DEL PROBLEMA 1

import numpy as np

def leevalida(m,M,txt):
    x=int(input(txt))
    while(not m<= x <= M):
        x=int(input("Error, ingrese denuevo: "))
    return x

n=leevalida(10,19,"n: ")
A=np.zeros((n,n))
b=leevalida(1,float("inf"),"b: ")


def bomba(x,y,m):
    A[x][y]+=5
    l=[1,0,-1]
    for i in l:
        for j in l:
            if(i!=0 or j!=0):
                A[x+i][y+j]+=3
    return A

for i in range(b):
    x=leevalida(1,n-2,f"x{i+1}")
    y=leevalida(1,n-2,f"y{i+1}")
    A=bomba(x,y,A)

print()
print(A)

n:  20
Error, ingrese denuevo:  5
Error, ingrese denuevo:  6
Error, ingrese denuevo:  12
b:  2
x1 1
y1 1
x2 7
y2 7



[[3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [3. 5. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 3. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 5. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 3. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
'''
Observaciones: Sección exclusiva para el comentarios de él/la revisor/a.

Puntaje : Sección exclusiva para el comentarios de él/la revisor/a.
'''
#  CÓDIGO DEL PROBLEMA 2
import numpy as np

def leevalida(m,M,txt):
    x=int(input(txt))
    while(not m<= x <= M):
        x=int(input("Error, ingrese denuevo: "))
    return x



f=leevalida(5,100,"filas: ")
c=leevalida(5,100,"columnas: ")
l=[]
for i in range(f):
    for j in range(c):
        x=int(input(f"R[{i+1}][{j+1}]="))
        if(x!=0):
            l.append([i,j,x])


m=np.array(l)
print()
print(m)

            



filas:  5
columnas:  7


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


R[1][1]= 7
R[1][2]= 0
R[1][3]= 0
R[1][4]= 0
R[1][5]= 0
R[1][6]= 1
R[1][7]= 0
R[2][1]= 0
R[2][2]= 0
R[2][3]= -1
R[2][4]= 0
R[2][5]= 0
R[2][6]= 0
R[2][7]= 6
R[3][1]= -9
R[3][2]= 0
R[3][3]= 0
R[3][4]= 00
R[3][5]= 0
R[3][6]= 0
R[3][7]= 0
R[4][1]= 0
R[4][2]= 0
R[4][3]= 0
R[4][4]= 0
R[4][5]= -3
R[4][6]= 0
R[4][7]= 0
R[5][1]= 0
R[5][2]= 8
R[5][3]= 0
R[5][4]= 0
R[5][5]= 0
R[5][6]= 0
R[5][7]= 0



[[ 0  0  7]
 [ 0  5  1]
 [ 1  2 -1]
 [ 1  6  6]
 [ 2  0 -9]
 [ 3  4 -3]
 [ 4  1  8]]


In [ ]:
'''
Observaciones: Sección exclusiva para el comentarios de él/la revisor/a.

Puntaje : Sección exclusiva para el comentarios de él/la revisor/a.
'''
#  CÓDIGO DEL PROBLEMA 3
import numpy as np

def leevalida(m,M,txt):
    x=int(input(txt))
    while(not m<= x <= M):
        x=int(input("Error, ingrese denuevo: "))
    return x

def es_cl(i,n,A):
    for k in range(n):
        if(k!=i):
            
    

n=leevalida(2,1000,"n: ")
m=leevalida(2,1000,"m: ")


m=np.zeros((n,m))
for i in range(n):
    for j in range(m):
        A[i][j]=int(input())
        


In [ ]:
# Desde esta celda en adelante puedes registrar lo que quieras,
# pruebas, intentos, etc.






