# CERTAMEN 2 PROGRAMACIÓN

NOMBRE ALUMNO: Jose Benjamin Junemann Vielma

MATRÍCULA    : 2024436813

SECCIÓN      : 0

PROFESOR     : Eduardo Esteban Mendez Ortiz 


In [ ]:
'''
Observaciones: Sección exclusiva para el comentarios de él/la revisor/a.

Puntaje : Sección exclusiva para el comentarios de él/la revisor/a.
'''

#  CÓDIGO DEL PROBLEMA 1

def leevalida(m,M,txt):
    s=input(txt) 
    if(s==""):      #Se devuelve para que el programa termine de recibir cadenas
        return s
    
    x=len(s)
    while(not m<= x <= M ):
        s=input("Error en el largo de la cadena ingrese denuevo:")
        if(s==""):    # Analogo al comentario anterior
            return s
        x=len(s)
    
    return s
    

# Verificadora de Letras

def letras(s):                       #Verifica si contiene solo los caracteres aceptados.
    roman="IVXLCDM"
    for car in s:
        if car not in roman:
            return False
    
    return True


# Verificadora de Repeticiones

def repeticiones(s):                 
    rep=1
    permi="IXCM"
    for i in range(1,len(s)):
        if(s[i]==s[i-1]):
            rep+=1
        else:
            rep=1
        if(s[i] in permi and rep>3):
            return False
        if(s[i] not in permi and rep>1):
            return False
    return True
    




## Funciones para verificar Orden


def permitidos(s):                         # Caracteres permitidos en el orden
    l=["IV","IX","XL","XC","CD","CM"]
    if s not in l:
        return False
    else:
        return True


def orden(s):                           #Verifica que se respete el orden de las letras
    l=["I","V","X","L","C","D","M"]
    for i in range(len(s)):
        if(i+1<len(s) and l.index(s[i])<l.index(s[i+1]) and not permitidos(s[i]+s[i+1])):
            return False
    return True

# s[i]+s[i+1] es una string de la forma "IV" por ejemplo.
# si el index de s[i] es menor al de s[i+1] etonces tiene menor valor por tanto podria no estar permitida.

    


def is_roman(s):                 #Funcion verificadora de todas las condiciones
    if(not letras(s)):
        return False

    if(not orden(s)):
        return False

    if (not repeticiones(s)):
        return False
        
    return True
    
sol=""    # Almacena la solucion.
while(True):
    s=leevalida(1,20,"Ingrese un Numero Romano:")
    if(s==""):
        break
    if(is_roman(s)):
        sol+="Numero Romano Correctamente Ingresado \n"
    else:
        sol+="Numero Romano Erroneo \n"

print(sol)


Ingrese un Numero Romano: MMMCMXCIX
Ingrese un Numero Romano: MMMCMXCVIII
Ingrese un Numero Romano: MMMXMVII
Ingrese un Numero Romano: IC
Ingrese un Numero Romano: D
Ingrese un Numero Romano: MCCCLLVV
Ingrese un Numero Romano: 


Numero Romano correctamente Ingresado 
Numero Romano correctamente Ingresado 
Numero Romano Erroneo 
Numero Romano Erroneo 
Numero Romano correctamente Ingresado 
Numero Romano Erroneo 



In [42]:
'''
Observaciones: Sección exclusiva para el comentarios de él/la revisor/a.

Puntaje : Sección exclusiva para el comentarios de él/la revisor/a.
'''
#  CÓDIGO DEL PROBLEMA 2

import numpy as np 

def leevalida(m,M,txt):
    x=int(input(txt))
    while(not m<= x <= M):
        x=int(input("Error, ingrese denuevo: "))
    return x

def leevalida2(x,y,n):               #Valida que almenos uno de los 2 sea distinto a 0
    while( x==0 and y==0):
        x=int(input(f"Error, las coordenadas NO pueden ser el punto (0,0) \nx{n}:"))
        y=int(input(f"y{n}:"))
    return [x,y]                      # retorna el par de numeros como lista


def distancia(l1,l2):                 #Distancia en R2
    deltax=(l1[0]-l2[0])**2
    deltay=(l1[1]-l2[1])**2
    return (deltax+deltay)**(0.5)


puntos=[[0,0]]                                   # Defino como punto inicial a (0,0)
n=leevalida(2,20,"Ingrese el nunero de islas: ")
for i in range(n):
    x=int(input(f"x{i+1}:"))
    y=int(input(f"y{i+1}:"))
    x,y=leevalida2(x,y,i+1)
    puntos.append([x,y])      #Ingreso la coordenada


md=np.zeros((n+1,n+1))   # Se crea matriz de distancias
for i in range(n+1):     
    for j in range(n+1):
        if(j>=i):        # Solo la parte superior de la matriz ya que la matriz es simetrica y se repetiria info
            md[i,j]=distancia(puntos[i],puntos[j])  

print()
print(md)  



Ingrese el nunero de islas:  3
x1: 1
y1: 2
x2: 4
y2: 3
x3: 2
y3: 4



[[0.         2.23606798 5.         4.47213595]
 [0.         0.         3.16227766 2.23606798]
 [0.         0.         0.         2.23606798]
 [0.         0.         0.         0.        ]]



[[ 0  0  7]
 [ 0  5  1]
 [ 1  2 -1]
 [ 1  6  6]
 [ 2  0 -9]
 [ 3  4 -3]
 [ 4  1  8]]


In [1]:
'''
Observaciones: Sección exclusiva para el comentarios de él/la revisor/a.

Puntaje : Sección exclusiva para el comentarios de él/la revisor/a.
'''
#  CÓDIGO DEL PROBLEMA 3



'\nObservaciones: Sección exclusiva para el comentarios de él/la revisor/a.\n\nPuntaje : Sección exclusiva para el comentarios de él/la revisor/a.\n'